name: CI

on:
  push:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v

  linux:
    runs-on: ubuntu-latest
    container: swift:6.3.3
    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Swift Package on Android
        uses: skiptools/swift-android-action@v2
        with:
          swift-version: '6.3'
          free-disk-space: true

  windows:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.3.2-release
          tag: 6.3.2-RELEASE
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
