name: CI

on:
  push:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v

  linux:
    runs-on: ubuntu-latest
    container: swift:6.3.3
    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
